services:
  - type: web
    name: dr-legal-bot
    plan: free
    envVars:
      - key: GROQ_API_KEY
        # Deixe o valor vazio aqui. O valor será definido no painel do Render.
        # Ou comente esta linha — o ideal é configurar no dashboard.
      - key: WHATSAPP_NUMERO
        value: 551199887766
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py